try(renv::activate())
args = commandArgs(trailingOnly=TRUE)
library(RWeka)
library(NoiseFiltersR)
library(kknn)
library(readr)

dataset <- paste("NoisyDatasets/", args[1], sep = "")
# df <- read.arff(dataset)
df <- read_csv(dataset, show_col_types = FALSE)  


# HARF algorithm
# set.seed(1)
df$class <- factor(df$class)
#out <- HARF(class~., data = df, nfolds = 5, agreementLevel = 0.7, ntrees = 300)
# out1 <- HARF(class~., data = df, nfolds = 5, agreementLevel = 0.8, ntrees = 300)
# out2 <- HARF(class~., data = df, nfolds = 5, agreementLevel = 0.9, ntrees = 300)
out3 <- HARF(class~., data = df, nfolds = 5, agreementLevel = 0.75, ntrees = 300)
out4 <- HARF(class~., data = df, nfolds = 5, agreementLevel = 0.85, ntrees = 300)
#output_dataset <- paste("NoisyDatasetsAfterFilters/HARF-70/", args[1], sep = "")
# output_dataset1 <- paste("NoisyDatasetsAfterFilters/HARF-80/", args[1], sep = "")
# output_dataset2 <- paste("NoisyDatasetsAfterFilters/HARF-90/", args[1], sep = "")
output_dataset3 <- paste("NoisyDatasetsAfterFilters/HARF-75/", args[1], sep = "")
output_dataset4 <- paste("NoisyDatasetsAfterFilters/HARF-85/", args[1], sep = "")
# write.arff(out$cleanData, file = output_dataset)
#write_csv(out$cleanData, file = output_dataset)
# write_csv(out1$cleanData, file = output_dataset1)
# write_csv(out2$cleanData, file = output_dataset2)
write_csv(out3$cleanData, file = output_dataset3)
write_csv(out4$cleanData, file = output_dataset4)
